### ISSUE TITLE
Still requires deprecated tool (OctoVersion.Tool version 0.3.59)

### ISSUE THREAD

**Issue by abowen** [OctopusDeploy/OctoVersion#234]
It's likely an issue on my end but can't see where it's happening

We're on Nuke, and converting from GitVersion to OctoVersion

In Build.cs

```
using Nuke.Common.Tools.OctoVersion;
...
    [Required]
    [OctoVersion(AutoDetectBranch = true)]
    readonly OctoVersionInfo OctoVersionInfo;
```

_build.csproj

```
  <ItemGroup>
    <PackageDownload Include="Octopus.OctoVersion.Tool" Version="[1.0.1]" />
  </ItemGroup>
```

Running my nuke command

```
PowerShell Desktop version 5.1.22621.4391
Microsoft (R) .NET SDK version 8.0.404
...
NUKE Execution Engine version 9.0.3 (Windows,.NETCoreApp,Version=v8.0)

12:57:42 [WRN] Could not inject value for Build.OctoVersionInfo
System.Exception: Missing package reference/download.
Run one of the following commands:
  - nuke :add-package OctoVersion.Tool --version 0.3.59
 ---> System.ArgumentException: Could not find package 'OctoVersion.Tool' using:
 - Project assets file 'C:\Users\me\git\my-project\build\obj\project.assets.json'
 - NuGet packages config 'C:\Users\me\git\my-project\build\_build.csproj'
   at Nuke.Common.Assert.NotNull[T](T obj, String message, String argumentExpression) in /_/source/Nuke.Utilities/Assert.cs:line 73
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageDirectory(String[] packageIds, String version) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 85
   --- End of inner exception stack trace ---
   at Nuke.Common.Assert.Fail(String message, Exception exception) in /_/source/Nuke.Utilities/Assert.cs:line 28
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageDirectory(String[] packageIds, String version) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 145
   at Nuke.Common.Tooling.NuGetToolPathResolver.GetPackageExecutable(String packageId, String packageExecutable, String version, String framework) in /_/source/Nuke.Tooling/NuGetToolPathResolver.cs:line 29
   at Nuke.Common.Tooling.NuGetToolAttribute.GetToolPath(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.ToolPath.cs:line 120
   at Nuke.Common.Tooling.ToolTasks.GetToolPath(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.ToolPath.cs:line 38
   at Nuke.Common.Tooling.ToolTasks.GetToolPathInternal(ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.ToolPath.cs:line 30
   at Nuke.Common.Tooling.ToolTasks.Run[T](ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 24
   at Nuke.Common.Tooling.ToolTasks.Run[TOptions,TResult](ToolOptions options) in /_/source/Nuke.Tooling/ToolTasks.Run.cs:line 45
   at Nuke.Common.Tools.OctoVersion.OctoVersionTasks.OctoVersionGetVersion(Configure`1 configurator) in /_/source/Nuke.Common/Tools/OctoVersion/OctoVersion.Generated.cs:line 35
   at Nuke.Common.Tools.OctoVersion.OctoVersionAttribute.GetValue(MemberInfo member, Object instance) in /_/source/Nuke.Common/Tools/OctoVersion/OctoVersionAttribute.cs:line 141
   at Nuke.Common.ValueInjection.ValueInjectionAttributeBase.TryGetValue(MemberInfo member, Object instance) in /_/source/Nuke.Build/Execution/Extensibility/ValueInjectionAttributeBase.cs:line 26
Member 'OctoVersionInfo' is required to be not null or empty
​
╬══════════════════════
║ Errors & Warnings
╬═════════════
​
[WRN] : Could not inject value for Build.OctoVersionInfo
```

If I install the additional tool, then it works. But then it requires us to have .NET 6.0 installed as well. 
I can do this as a work around but would ideally like to fix the root cause

**Comment by matt-richardson** [comment]
Hi @abowen - this is actually a change needed in Nuke - [here, specifically](https://github.com/nuke-build/nuke/blob/develop/source/Nuke.Common/Tools/OctoVersion/OctoVersion.json#L8).

AFAIK, @matkoch is aware of it.

**Comment by abowen** [comment]
Thank you

Closing this issue and I'll follow up with them / create PR if required
